---
image: nixos/unstable
tasks:
  - build: |
      nix run -f advent-of-code-2020 day1.haskell -c day1-hs < advent-of-code-2020/day1/input
      nix run -f advent-of-code-2020 day2.python  -c day2-py < advent-of-code-2020/day2/input
      nix run -f advent-of-code-2020 day3.haskell -c day3-hs < advent-of-code-2020/day3/input
      nix run -f advent-of-code-2020 day4.haskell -c day4-hs < advent-of-code-2020/day4/input
