---
image: nixos/unstable
tasks:
  - day1: nix run -f advent-of-code-2020 day1.haskell -c day1-hs < advent-of-code-2020/day1/input
  - day2: nix run -f advent-of-code-2020 day2.python -c day2-py < advent-of-code-2020/day2/input
  - day3: nix run -f advent-of-code-2020 day3.haskell -c day3-hs < advent-of-code-2020/day3/input
  - day4: nix run -f advent-of-code-2020 day4.haskell -c day4-hs < advent-of-code-2020/day4/input
